<a href="https://colab.research.google.com/github/sojiseung/sjs0424/blob/main/m3_%EB%B6%84%EC%84%9D_%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/240605_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###  아래 가이드에 따라서 1000명의 고객 구매데이터를 생성하고 아래사항을 수행하세요(관측치 10000개)

#### Q1. 고객 속성(id, 성별, 연령, 거주지역) 데이터와 거래 데이터를 통합한 데이터 프레임 df를 생성하세요.
고객별 속성 데이터
- id : 1 ~ 1000 고객 번호
- gender : 0,1 정수 난수 생성
- age : 0 ~ 80사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성

거래 데이터
- no : 1 ~ 10000번 일련번호
- day : 요일
- date : 2020-01-01 ~ 2021-12-31 사이의 날짜 1000개 생성
- product_20 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10 ~ 30
- product_21 : 고가제품(10), 중가제품(20), 저가제품(30)로 구분제품코드 10 ~ 30
- price_20 : 1000 ~ 50000 사이 실수 난수 생성
- price_21 : 1000 ~ 50000 사이 실수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- quantity_21 : 1 ~ 100 사이 정수 난수 생성
- time_20 : 01 ~ 24 사이 정수 난수 생성
- time_21 : 01 ~ 24 사이 정수 난수 생성
- amount_20 : price_20 * quantity_20
- amount_21 : price_21 * quantity_21

#### Q2. df를 수정하여 3가지 이상의 인사이트를 포함한 데이터 셋으로 변환하세요

#### Q3. df 를 탐색적 분석을 통하여 인사이트를 도출하세요.

merge customer기준으로 하기
replace = True => choice

In [ ]:
import pandas as pd
import numpy as np
import random
from datetime import datetime
import time

In [ ]:
product_20 = [10,20,30]
product_21 = [10,20,30]
dtt = pd.date_range(start='2020-01-01',end='2021-12-31').date
dates = list(np.random.choice(dtt, replace=True) for i in range(10000))
date1 = pd.Series(dates)
date = pd.to_datetime(date1)
days = date.dt.day_name()

product = pd.DataFrame({
    'id' : np.random.randint(1,1001,10000),
    'no' : range(1,10001),
    'date' : dates,
    'day' : days,
    'product_20' : (np.random.choice(product_20, replace=True) for i in range(10000)),
    'product_21' : (np.random.choice(product_21, replace=True) for i in range(10000)),
    'price_20' : (np.random.uniform(1000,50000) for i in range(10000)),
    'price_21' : (np.random.uniform(1000,50000) for i in range(10000)),
    'quantity_20' : (np.random.randint(1,101,10000)),
    'quantity_21' : (np.random.randint(1,101,10000)),
    'time_20' : np.random.randint(1,25,10000),
    'time_21' : np.random.randint(1,25,10000)
})
product['price_20'] = round(product['price_20'],2)
product['price_21'] = round(product['price_21'],2)
product['amount_20'] = round(product['price_20'] * product['quantity_20'],2)
product['amount_21'] = round(product['price_21'] * product['quantity_21'],2)

rg = ['suwon','seoul','incheon','busan','jeju']
customer = pd.DataFrame({
    'id' : range(1,1001),
    'gender' : (np.random.randint(0,2) for i in range(1000)),
    'age' : (np.random.randint(10,80) for i in range(1000)),
    'region' : (np.random.choice(rg, replace=True) for i in range(1000))
})
pro_cus = pd.merge(customer, product, on='id', how='inner')
pro_cus.head()

,id,gender,age,region,no,date,day,product_20,product_21,price_20,price_21,quantity_20,quantity_21,time_20,time_21,amount_20,amount_21
0,1,0,72,seoul,224,2020-09-11,Friday,10,30,40931.20,30755.38,53,51,1,14,2169353.60,1568524.38
1,1,0,72,seoul,799,2021-06-12,Saturday,30,20,28384.69,2695.90,59,37,1,19,1674696.71,99748.30
2,1,0,72,seoul,912,2021-06-23,Wednesday,10,10,41218.05,43672.22,96,47,7,14,3956932.80,2052594.34
3,1,0,72,seoul,1483,2020-02-16,Sunday,10,10,10552.77,38194.47,73,61,16,21,770352.21,2329862.67
4,1,0,72,seoul,2101,2021-04-14,Wednesday,10,30,16454.23,22916.74,53,56,4,20,872074.19,1283337.44